### ISSUE TITLE
Add Solana to it

### ISSUE THREAD

**Issue by Yhodhan** [Axl-91/rust-project#1]
hello i came across with your repo and i wanted to ask you, if you have consider the idea to add blockchain into it, especially solana since it is a rust code base.

**Comment by Axl-91** [comment]
https://www.youtube.com/watch?v=wLg04uu2j2o

**Comment by Yhodhan** [comment]
> https://www.youtube.com/watch?v=wLg04uu2j2o

oh i see, that is sad, thanks for the quick reply!
